### ISSUE TITLE
[feat] API 구현 형식 가이드 - 동화 정보 API

### ISSUE THREAD

**Issue by alsrudrl1220** [GDSC-CAU/FTIsland-BE#9]
## 📌 Issue 내용

- 동화 정보 API 구현을 통한 API 구현 형식 가이드 제작

<br/>

## 📝 TO DO

- [x] controller, dto, entity, repository, service 로 변경
- [x] 동화 정보 API 구현

<br/>

## 💌 비고

-

**Comment by RumosZin** [comment]
민경님 혹시 제가 지금 작업한 내용 merge 하면 그때부터 작업 가능하실까요??

**Comment by RumosZin** [comment]
작업 완료 했습니다!!

**Comment by alsrudrl1220** [comment]
넹 확인했습니다!
